In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/opensky_raw.csv')
df.head()

,icao24,callsign,origin_country,timestamp,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,geo_altitude,s.category
0,39de4e,TVF72AP,France,1.775320e+09,-3.0203,42.6994,11277.60,False,213.09,230.58,-0.33,11521.44,0
1,c07d0b,CGVJE,Canada,1.775320e+09,-74.4022,45.6474,251.46,False,46.55,249.96,-0.33,320.04,0
2,e8027c,LPE2454,Chile,1.775320e+09,-79.3632,-8.3513,10370.82,False,236.05,333.32,0.00,11079.48,0
3,ab1644,UAL2017,United States,1.775320e+09,-87.1179,40.3284,10363.20,False,224.95,151.15,5.85,10652.76,0
4,80162c,NaN,India,1.775320e+09,73.0471,18.9823,106.68,False,87.74,262.25,8.13,22.86,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014322 entries, 0 to 1014321
Data columns (total 13 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   icao24          1014322 non-null  object
 1   callsign        998521 non-null   object
 2   origin_country  1014258 non-null  object
 3   timestamp       1006498 non-null  float64
 4   longitude       1006498 non-null  float64
 5   latitude        1006498 non-null  float64
 6   baro_altitude   937122 non-null   float64
 7   on_ground       1014322 non-null  bool
 8   velocity        1013888 non-null  float64
 9   true_track      1014322 non-null  float64
 10  vertical_rate   941616 non-null   float64
 11  geo_altitude    931313 non-null   float64
 12  s.category      1014322 non-null  int64
dtypes: bool(1), float64(8), int64(1), object(3)
memory usage: 93.8+ MB

In [4]:
df.isnull().sum()

icao24                0
callsign          15801
origin_country       64
timestamp          7824
longitude          7824
latitude           7824
baro_altitude     77200
on_ground             0
velocity            434
true_track            0
vertical_rate     72706
geo_altitude      83009
s.category            0
dtype: int64

In [5]:
import sys
import os

In [6]:
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(parent_dir)
from preprocessing.data_cleaning import clean_df
from preprocessing.feature_engineering import feature_engineering
from preprocessing.sklearn_utilities import group_shuffle_split, scale_dataset 
from preprocessing.utilities import sort_values, num_aircrafts, initialise_features_and_target, initialise_df
from rnn_sequences import save_sequences

In [7]:
df_sorted = sort_values(df)

In [8]:
df_clean = clean_df(df_sorted)

In [9]:
df_clean.isnull().sum()

icao24             0
origin_country    64
timestamp          0
longitude          0
latitude           0
baro_altitude      0
on_ground          0
velocity           0
true_track         0
vertical_rate      0
s.category         0
dtype: int64

In [10]:
df_engineered = feature_engineering(df_clean)

In [11]:
df_engineered.isnull().sum()

icao24              0
origin_country     64
timestamp           0
longitude           0
latitude            0
baro_altitude       0
on_ground           0
velocity            0
true_track          0
vertical_rate       0
s.category          0
delta_time          0
track_sin           0
track_cos           0
hour_sin            0
hour_cos            0
prev_velocity       0
acceleration        0
prev_track          0
turn_rate           0
climb_phase         0
delta_latitude      0
delta_longitude     0
dtype: int64

In [12]:
features, target = initialise_features_and_target()

In [15]:
features

['velocity',
 'vertical_rate',
 'baro_altitude',
 'delta_time',
 'track_sin',
 'track_cos',
 'latitude',
 'longitude',
 'acceleration',
 'turn_rate',
 'climb_phase',
 'hour_sin',
 'hour_cos']

In [14]:
training_set, testing_set = group_shuffle_split(df_engineered)
testing_set

,icao24,origin_country,timestamp,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,...,track_cos,hour_sin,hour_cos,prev_velocity,acceleration,prev_track,turn_rate,climb_phase,delta_latitude,delta_longitude
3718,008deb,South Africa,1970-01-01 00:00:01.775320176,19.1815,-33.7011,4191.00,False,156.32,215.63,-6.50,...,-0.812796,0.0,1.0,0.00,1.563200e+02,0.00,-1.443700e+02,-1,0.0000,0.0000
14872,008deb,South Africa,1970-01-01 00:00:01.775320198,19.1610,-33.7253,4084.32,False,151.55,214.77,-5.53,...,-0.821448,0.0,1.0,156.32,-2.168182e+08,215.63,-3.909091e+07,-1,-0.0242,-0.0205
26048,008deb,South Africa,1970-01-01 00:00:01.775320215,19.1457,-33.7437,3992.88,False,147.72,215.07,-6.18,...,-0.818451,0.0,1.0,151.55,-2.252941e+08,214.77,1.764706e+07,-1,-0.0184,-0.0153
37223,008deb,South Africa,1970-01-01 00:00:01.775320228,19.1331,-33.7586,3909.06,False,145.32,215.49,-6.18,...,-0.814217,0.0,1.0,147.72,-1.846154e+08,215.07,3.230769e+07,-1,-0.0149,-0.0126
48399,008deb,South Africa,1970-01-01 00:00:01.775320242,19.1204,-33.7732,3802.38,False,143.02,216.66,-6.83,...,-0.802193,0.0,1.0,145.32,-1.642857e+08,215.49,8.357143e+07,-1,-0.0146,-0.0127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202527,e80623,Chile,1970-01-01 00:00:01.775320173,-71.8675,-45.4179,4290.06,False,176.37,169.41,-10.08,...,-0.982967,0.0,1.0,176.37,0.000000e+00,169.41,0.000000e+00,-1,0.0000,0.0000
213656,e80623,Chile,1970-01-01 00:00:01.775320173,-71.8675,-45.4179,4290.06,False,176.37,169.41,-10.08,...,-0.982967,0.0,1.0,176.37,0.000000e+00,169.41,0.000000e+00,-1,0.0000,0.0000
224793,e80623,Chile,1970-01-01 00:00:01.775320173,-71.8675,-45.4179,4290.06,False,176.37,169.41,-10.08,...,-0.982967,0.0,1.0,176.37,0.000000e+00,169.41,0.000000e+00,-1,0.0000,0.0000
235927,e80623,Chile,1970-01-01 00:00:01.775320173,-71.8675,-45.4179,4290.06,False,176.37,169.41,-10.08,...,-0.982967,0.0,1.0,176.37,0.000000e+00,169.41,0.000000e+00,-1,0.0000,0.0000
247043,e80623,Chile,1970-01-01 00:00:01.775320173,-71.8675,-45.4179,4290.06,False,176.37,169.41,-10.08,...,-0.982967,0.0,1.0,176.37,0.000000e+00,169.41,0.000000e+00,-1,0.0000,0.0000

In [16]:
df_scaled = scale_dataset(training_set, testing_set, features)
df_scaled

(        icao24 origin_country                     timestamp  longitude  \
 8475    008080   South Africa 1970-01-01 00:00:01.775320176   1.427958
 19638   008080   South Africa 1970-01-01 00:00:01.775320197   1.428002
 30817   008080   South Africa 1970-01-01 00:00:01.775320215   1.428037
 42000   008080   South Africa 1970-01-01 00:00:01.775320228   1.428064
 53173   008080   South Africa 1970-01-01 00:00:01.775320242   1.428037
 ...        ...            ...                           ...        ...
 949107  e94c88        Bolivia 1970-01-01 00:00:01.775321160  -0.284748
 959989  e94c88        Bolivia 1970-01-01 00:00:01.775321160  -0.284748
 970873  e94c88        Bolivia 1970-01-01 00:00:01.775321160  -0.284748
 981739  e94c88        Bolivia 1970-01-01 00:00:01.775321160  -0.284748
 992604  e94c88        Bolivia 1970-01-01 00:00:01.775321160  -0.284748

         latitude  baro_altitude  on_ground  velocity  true_track  \
 8475   -4.965554      -0.142222      False  0.306071      175.91
 19638  -4.968244      -0.185249      False  0.276170      176.02
 30817  -4.970537      -0.219670      False  0.258114      176.15
 42000  -4.972124      -0.245486      False  0.240403      176.12
 53173  -4.973862      -0.273024      False  0.196011      193.58
 ...          ...            ...        ...       ...         ...
 949107 -2.459098       0.957544      False  0.945044      342.24
 959989 -2.459098       0.957544      False  0.945044      342.24
 970873 -2.459098       0.957544      False  0.945044      342.24
 981739 -2.459098       0.957544      False  0.945044      342.24
 992604 -2.459098       0.957544      False  0.945044      342.24

         vertical_rate  ...  track_cos  hour_sin  hour_cos  prev_velocity  \
 8475        -1.874107  ...  -1.381604       0.0       0.0           0.00
 19638       -1.874107  ...  -1.381797       0.0       0.0         180.51
 30817       -1.874107  ...  -1.382018       0.0       0.0         177.91
 42000       -1.874107  ...  -1.381968       0.0       0.0         176.34
 53173       -1.802150  ...  -1.345330       0.0       0.0         174.80
 ...               ...  ...        ...       ...       ...            ...
 949107       0.040390  ...   1.401809       0.0       0.0         236.07
 959989       0.040390  ...   1.401809       0.0       0.0         236.07
 970873       0.040390  ...   1.401809       0.0       0.0         236.07
 981739       0.040390  ...   1.401809       0.0       0.0         236.07
 992604       0.040390  ...   1.401809       0.0       0.0         236.07

         acceleration  prev_track  turn_rate  climb_phase  delta_latitude  \
 8475        0.001038        0.00   0.016820    -1.553478          0.0000
 19638      -0.182139      175.91   0.022995    -1.553478         -0.0339
 30817      -0.128008      176.02   0.025335    -1.553478         -0.0289
 42000      -0.174227      176.15   0.014099    -1.553478         -0.0200
 53173      -0.406883      176.12   1.487172    -1.553478         -0.0219
 ...              ...         ...        ...          ...             ...
 949107      0.001037      342.24   0.016820     0.114597          0.0000
 959989      0.001037      342.24   0.016820     0.114597          0.0000
 970873      0.001037      342.24   0.016820     0.114597          0.0000
 981739      0.001037      342.24   0.016820     0.114597          0.0000
 992604      0.001037      342.24   0.016820     0.114597          0.0000

         delta_longitude
 8475             0.0000
 19638            0.0026
 30817            0.0021
 42000            0.0016
 53173           -0.0016
 ...                 ...
 949107           0.0000
 959989           0.0000
 970873           0.0000
 981739           0.0000
 992604           0.0000

 [907363 rows x 23 columns],
         icao24 origin_country                     timestamp  longitude  \
 3718    008deb   South Africa 1970-01-01 00:00:01.775320176   1.266386
 14872   008deb   South Africa 1970-01-01 00:00:01.775320198   1.266040
 26048   008deb   South Africa 1970-01-01 00:00:01.775320215   1.265782
 37223   008deb   South Africa 1970-01-01 00:00:01.775320228   1.265570
 48399   008deb   South Africa 1970-01-01 00:00:01.775320242   1.265356
 ...        ...            ...                           ...        ...
 202527  e80623          Chile 1970-01-01 00:00:01.775320173  -0.269522
 213656  e80623          Chile 1970-01-01 00:00:01.775320173  -0.269522
 224793  e80623          Chile 1970-01-01 00:00:01.775320173  -0.269522
 235927  e80623          Chile 1970-01-01 00:00:01.775320173  -0.269522
 247043  e80623          Chile 1970-01-01 00:00:01.775320173  -0.269522

         latitude  baro_altitude  on_ground  velocity  true_track  \
 3718   -5.601474      -0.574211      False  0.027872      215.63
 14872  -5.603394      -0.598306      False -0.026985      214.77
 26048  -5.604854      -0.618959      False -0.071033      215.07
 37223  -5.606036      -0.637891      False -0.098634      215.49
 48399  -5.607195      -0.661986      False -0.125085      216.66
 ...          ...            ...        ...       ...         ...
 202527 -6.531168      -0.551837      False  0.258459      169.41
 213656 -6.531168      -0.551837      False  0.258459      169.41
 224793 -6.531168      -0.551837      False  0.258459      169.41
 235927 -6.531168      -0.551837      False  0.258459      169.41
 247043 -6.531168      -0.551837      False  0.258459      169.41

         vertical_rate  ...  track_cos  hour_sin  hour_cos  prev_velocity  \
 3718        -1.376948  ...  -1.117998       0.0       0.0           0.00
 14872       -1.165438  ...  -1.130350       0.0       0.0         156.32
 26048       -1.307172  ...  -1.126071       0.0       0.0         151.55
 37223       -1.307172  ...  -1.120027       0.0       0.0         147.72
 48399       -1.448906  ...  -1.102862       0.0       0.0         145.32
 ...               ...  ...        ...       ...       ...            ...
 202527      -2.157575  ...  -1.360925       0.0       0.0         176.37
 213656      -2.157575  ...  -1.360925       0.0       0.0         176.37
 224793      -2.157575  ...  -1.360925       0.0       0.0         176.37
 235927      -2.157575  ...  -1.360925       0.0       0.0         176.37
 247043      -2.157575  ...  -1.360925       0.0       0.0         176.37

         acceleration  prev_track  turn_rate  climb_phase  delta_latitude  \
 3718        0.001038        0.00   0.016820    -1.553478          0.0000
 14872      -0.319746      215.63  -0.029268    -1.553478         -0.0242
 26048      -0.332286      214.77   0.037625    -1.553478         -0.0184
 37223      -0.272102      215.07   0.054910    -1.553478         -0.0149
 48399      -0.242024      215.49   0.115348    -1.553478         -0.0146
 ...              ...         ...        ...          ...             ...
 202527      0.001037      169.41   0.016820    -1.553478          0.0000
 213656      0.001037      169.41   0.016820    -1.553478          0.0000
 224793      0.001037      169.41   0.016820    -1.553478          0.0000
 235927      0.001037      169.41   0.016820    -1.553478          0.0000
 247043      0.001037      169.41   0.016820    -1.553478          0.0000

         delta_longitude
 3718             0.0000
 14872           -0.0205
 26048           -0.0153
 37223           -0.0126
 48399           -0.0127
 ...                 ...
 202527           0.0000
 213656           0.0000
 224793           0.0000
 235927           0.0000
 247043           0.0000

 [99135 rows x 23 columns],
 StandardScaler())